FROM python

RUN mkdir /data
RUN mkdir /app

ADD sync.py /app
ADD budget /app/budget
ADD requirements.txt /app

RUN pip install -r /app/requirements.txt

WORKDIR /data

CMD python /app/sync.py --periodic --config $CONFIG_URL